FROM maven:3-jdk-8 AS build
WORKDIR /app
COPY . /app
RUN mvn clean install -Pfrontend

FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=build /app/target/server-*.jar /app
EXPOSE 8080

CMD java -jar server-*.jar
